---
- name: Setting up backend
  remote_user: root
  hosts: gluster_servers
  gather_facts: false

  vars:
     # Set a disk type - Default: JBOD
     # Options: JBOD, RAID6, RAID10
     gluster_infra_disktype: RAID6

     # RAID6 and RAID10 diskcount
     gluster_infra_diskcount: 10

     # Stripe unit size always in KiB
     gluster_infra_stripe_unit_size: 128

     # Variables for creating volume group
     #
     gluster_infra_vg_name: glusterfs_backend_vg
     gluster_infra_pvs: /dev/vdb,/dev/vdc

     # Create a thinpool
     gluster_infra_lv_thinpoolname: glusterfs_backend_thinpool

     # Create a thin volume
     gluster_infra_lv_logicalvols:
        - { lvname: 'glusterstore_thinlv', lvsize: '500G' }

     # Create a thick volume name
     gluster_infra_lv_thicklvname: glusterfs_thicklv
     gluster_infra_lv_thicklvsize: 20G

     # Mount the devices
     gluster_infra_mount_devices:
        - { path: '/mnt/thinv',   lv: glusterstore_thinlv }
        - { path: '/mnt/thicklv', lv: "{{ gluster_infra_lv_thicklvname }}"}

  roles:
     - gluster.infra
