# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
        
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Install glusteransible-infra rpm
        run: sudo yum install https://copr-be.cloud.fedoraproject.org/results/sac/gluster-ansible/epel-8-x86_64/01708242-gluster-ansible-infra/gluster-ansible-infra-1.0.4-15.el8.noarch.rpm -y 
      
      - name: clone the repo
        run: git clone https://github.com/pkesavap/gluster-ansible-infra.git && cd gluster-ansible-infra
      
      - name:  Initiate Test for gluster-ansible
        run: sudo ansible-playbook ./tests/test.yml

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
